### ISSUE TITLE
Subsetting doesn't work

### ISSUE THREAD

**Issue by agrueneberg** [QuantGen/symDMatrix#3]
```R
> G3[1:260, ]
Error in as.hi.integer(as.integer(x), ...) : 
  positive subscripts out of range
```

**Comment by gdlc** [comment]
???

**Comment by agrueneberg** [comment]
My bad! This was my attempt to properly balance the blocks in getG.symDMatrix, but the problem is a lot more widespread in the symDMatrix package than I thought. For now, it's probably not that important to fix, so I reverted the commit.
