### ISSUE TITLE
Support adding blocks

### ISSUE THREAD

**Issue by agrueneberg** [QuantGen/symDMatrix#7]
Right now it is tricky to add a new block because the code assumes the same block size for all blocks except the last one. We need a more dynamic approach to calculate offsets.

**Comment by gdlc** [comment]
makes sense.  I guess we need to add a function, like the old 'chunks', and use it internally to figure out indices.

blocks.symDMatrix=function(x){
          nBlocks=length(x@data)
          n=rep(NA,nBlocks)
          for(i in 1:nBlocks){ n[i]=nrow(x@data[[1]]) }
          n
}

**Comment by agrueneberg** [comment]
Closed due to inactivity.
